### ISSUE TITLE
Unsupported type of report in Grafana integration example

### ISSUE THREAD

**Issue by jenoOvchi** [evidentlyai/evidently#136]
Hi!

Today i've try to reproduce Grafana integration example and find next error - in config.yaml file (https://github.com/evidentlyai/evidently/blob/main/examples/integrations/grafana_monitoring_service/config.yaml) in section service.monitors now two values are defined: [ "data_drift", "regression_performance" ]. But if i try to run this example without configuration changes app.py fails with next error:
```bash
evidentlyai-demo-evidently_service-1  | [2022-02-03 07:01:44,758] ERROR in app: Exception on /iterate [POST]
evidentlyai-demo-evidently_service-1  | Traceback (most recent call last):
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
evidentlyai-demo-evidently_service-1  |     response = self.full_dispatch_request()
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
evidentlyai-demo-evidently_service-1  |     rv = self.handle_user_exception(e)
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
evidentlyai-demo-evidently_service-1  |     rv = self.dispatch_request()
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
evidentlyai-demo-evidently_service-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
evidentlyai-demo-evidently_service-1  |   File "/app/app.py", line 132, in iterate
evidentlyai-demo-evidently_service-1  |     SERVICE.iterate(new_rows=pandas.DataFrame.from_dict(item))
evidentlyai-demo-evidently_service-1  |   File "/app/app.py", line 92, in iterate
evidentlyai-demo-evidently_service-1  |     for metric, value, labels in self.monitoring.metrics():
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/evidently/model_monitoring/monitoring.py", line 61, in metrics
evidentlyai-demo-evidently_service-1  |     for metric in monitor.metrics(self.analyzers_results):
evidentlyai-demo-evidently_service-1  |   File "/usr/local/lib/python3.8/site-packages/evidently/model_monitoring/monitors/regression_performance.py", line 24, in metrics
evidentlyai-demo-evidently_service-1  |     metrics = results['metrics']
evidentlyai-demo-evidently_service-1  | TypeError: 'RegressionPerformanceAnalyzerResults' object is not subscriptable
```

Without second key ("regression_performance") in service.monitors it works correctly.

**Comment by Tapot** [comment]
Hi @jenoOvchi,

There was a problem after analyzers moved to typed results, now it is fixed in the main branch

In the next release, `regression_performance` will be ok

**Comment by jenoOvchi** [comment]
> Hi @jenoOvchi,
> 
> There was a problem after analyzers moved to typed results, now it is fixed in the main branch
> 
> In the next release, `regression_performance` will be ok

Ok, thanks.

**Comment by Tapot** [comment]
And in the example, we have data drift Grafana dashboard only, a dashboard for regression will be added later, after the release

**Comment by Tapot** [comment]
For now `regression_performance` should be ok.

**Comment by jenoOvchi** [comment]
> For now `regression_performance` should be ok.

Ok, thanks.
