### ISSUE TITLE
Collector key error on storage buffer

### ISSUE THREAD

**Issue by Mohammadabd** [evidentlyai/evidently#1364]
I have been trying to run the example [here](https://github.com/evidentlyai/evidently/blob/main/examples/integrations/collector_service/example_report.py) but getting this error. Seems that id is not initialized in `_buffer` dictionary.  Here is the error log

INFO:     Started server process [15549]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:65386 - "POST /default_test HTTP/1.1" 500 Internal Server Error
ERROR - 2024-11-12 21:04:09,110 - evidently.collector.app - app - Check snapshots factory error: 'default_test'
Traceback (most recent call last):
  File "/Users/m0a0mlk/envs/monitoring/lib/python3.9/site-packages/evidently/collector/app.py", line 232, in check_service_snapshots_periodically
    await check_snapshots_factory(service, service.storage)
  File "/Users/m0a0mlk/envs/monitoring/lib/python3.9/site-packages/evidently/collector/app.py", line 131, in check_snapshots_factory
    await create_snapshot(collector, storage)
  File "/Users/m0a0mlk/envs/monitoring/lib/python3.9/site-packages/evidently/collector/app.py", line 136, in create_snapshot
    async with storage.lock(collector.id):
  File "/Users/m0a0mlk/envs/monitoring/lib/python3.9/site-packages/evidently/collector/storage.py", line 52, in lock
    return self._locks[id]
KeyError: 'default_test'
^CERROR - 2024-11-12 21:04:14,128 - evidently.collector.app - app - Check snapshots factory error: 'default_test'

**Comment by lchunleo** [comment]
facing the same issue when running the sample. the collector shows error and the sample program should internal error of 500
