### ISSUE TITLE
Request Entity Too Large in v0.5.1

### ISSUE THREAD

**Issue by oleg-savko** [evidentlyai/evidently#1404]
In version v0.5.1 starts a problem with `Request Entity Too Large` on save snapshot.
```

File "/home/airflow/.local/lib/python3.11/site-packages/evidently/ui/managers/projects.py", line 159, in add_snapshot
    await self.project_metadata.add_snapshot(project_id, snapshot, blob)
  File "/home/airflow/.local/lib/python3.11/site-packages/evidently/ui/workspace/remote.py", line 206, in add_snapshot
    return self._request(f"/api/projects/{project_id}/snapshots", "POST", body=snapshot.dict())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/evidently/ui/workspace/remote.py", line 137, in _request
    raise EvidentlyServiceError(details)
evidently.ui.errors.EvidentlyServiceError: Request Entity Too Large
```

Seems it correspond to new version of litestar whitch has this new features and restrict it by default to 10Mb:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/87657a03-5fd4-4a06-8e0d-f341def8737b" />

Workaround: need add a way to specify increase max request size (snapshots can be much more then 10mb).

**Comment by DimaAmega** [comment]
Hi @oleg-savko

Nice catch! Thanks for it!

Would you like to contribute 😊?

Just add  `request_max_body_size = None,` to this [file](https://github.com/evidentlyai/evidently/blob/main/src/evidently/ui/components/base.py#L50) before `**self.kwargs`

I guess this is nice to have no limits by default in application layer (and good to have limits in other layers like proxy (nginx etc.))

**Comment by abhishek-pattern** [comment]
I am facing this same issue in version 0.7.3

```
---------------------------------------------------------------------------
EvidentlyError                            Traceback (most recent call last)
Cell In[83], [line 1](vscode-notebook-cell:?execution_count=83&line=1)
----> [1](vscode-notebook-cell:?execution_count=83&line=1) workspace.add_run("0196a49d-bfa5-7de2-be6d-378aba5c2a6e", rep, include_data=False)

EvidentlyError: Request Entity Too Large
```

Also from above comments I came across , like `request_max_body_size = None` may solve the issue, but how to pass this ?
A details steps on this would be helpful.
