### ISSUE TITLE
Exception on Get started code execution

### ISSUE THREAD

**Issue by ankxyz** [evidentlyai/evidently#4]
Hello.

If I try to run code from [Get started](https://github.com/evidentlyai/evidently#getting-started) as is:

```python
import pandas as pd
from sklearn import datasets

from evidently.dashboard import Dashboard
from evidently.tabs import DriftTab, CatTargetDriftTab

iris = datasets.load_iris()
iris_frame = pd.DataFrame(iris.data, columns = iris.feature_names)

iris_data_drift_report = Dashboard(iris_frame[:100], iris_frame[100:], tabs = [DriftTab])
iris_data_drift_report.save("reports/my_report.html")

iris_data_drift_report = Dashboard(iris_frame[:100], iris_frame[100:], tabs = [DriftTab, CatTargetDriftTab])
iris_data_drift_report.save("reports/my_report_with_2_tabs.html")
```

I get error:

```python
Traceback (most recent call last):
  File "get_started.py", line 15, in <module>
    iris_data_drift_report.save("reports/my_report_with_2_tabs.html")
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/dashboard/dashboard.py", line 161, in save
    f.write(self.__render(file_html_template))
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/dashboard/dashboard.py", line 141, in __render
    tab_widgets = [t.info() for t in self.tabsData]
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/dashboard/dashboard.py", line 141, in <listcomp>
    tab_widgets = [t.info() for t in self.tabsData]
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/tabs/base_tab.py", line 27, in info
    return [w.get_info() for w in self.widgets]
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/tabs/base_tab.py", line 27, in <listcomp>
    return [w.get_info() for w in self.widgets]
  File "/home/alex/Dev/venv/lib/python3.8/site-packages/evidently/widgets/cat_target_pred_feature_table_widget.py", line 29, in get_info
    raise ValueError("neither target nor prediction data provided")
ValueError: neither target nor prediction data provided
```

---

As I understood, *CatTargetDriftTab* requires target column. So, if I add the target column everything is ok:

```python
import pandas as pd
from sklearn import datasets

from evidently.dashboard import Dashboard
from evidently.tabs import DriftTab, CatTargetDriftTab

iris = datasets.load_iris()
iris_frame = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_frame['target'] = iris.target

iris_data_drift_report = Dashboard(iris_frame[:100], iris_frame[100:], tabs = [DriftTab])
iris_data_drift_report.save("reports/my_report.html")

iris_data_drift_report = Dashboard(iris_frame[:100], iris_frame[100:], tabs = [DriftTab, CatTargetDriftTab])
iris_data_drift_report.save("reports/my_report_with_2_tabs.html")
```

(Line added: `iris_frame['target'] = iris.target`)

---

Please fix `Get started` section.

---
Regargs, Alex.

**Comment by elenasamuylova** [comment]
Hi Alex, thanks for sharing! 

We made it more clear in the documentation and promoted this info to the Get Started section. 

Please let us know if anything else raises questions - the documentation is work in progress :)

**Comment by emeli-dral** [comment]
The documentation is updated.
